export const STATE_LIST_REQUEST = "STATE_LIST_REQUEST";
export const STATE_LIST_SUCCESS = "STATE_LIST_SUCCESS";
export const STATE_LIST_FAIL = "STATE_LIST_FAIL";

export const STATE_DETAILS_REQUEST = "STATE_DETAILS_REQUEST";
export const STATE_DETAILS_SUCCESS = "STATE_DETAILS_SUCCESS";
export const STATE_DETAILS_FAIL = "STATE_DETAILS_FAIL";
